# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b852e5f21c19e5757f809bb58a20622f403bc9f5d134700e7125692fe78fb129a0161d03d034f2406179199947bc32de172a48d5ac76c989691e6ba95a36677e

test:
  secret_key_base: 457b8ea41c11fece3ecc3e1448102ba2a76ec7474ca320f7a28e83211cba3a1022bad502205f367b39d333eed671440eb3765d4ecc1c6d3c3fa18f6878d934a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
